notifications:
  email:
    recipients:
      - peter.kruczkiewicz@gmail.com
    on_success: change
    on_failure: change

language: python
python:
  - '3.5'
  - '3.6'

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update;

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --add channels defaults
  - conda config --add channels conda-forge
  - conda config --add channels bioconda
  - conda install mash numpy pandas click -y
  - python setup.py -q install
  - pip install pytest

script:
  - refseq_masher --version
  - refseq_masher --help
  - refseq_masher matches --help
  - refseq_masher contains --help
  - pytest
